### ISSUE TITLE
Regarding URL handling of destination

### ISSUE THREAD

**Issue by nipun0212** [SAP/cloud-sdk-js#3552] opened 2023-02-21 05:31 UTC
Hi,
While executing the request with a destination where the resource URL is repeated, the call fails while the same call passes in java SDK.
Ex  
https://my300470-api.s4hana.ondemand.com**/sap/opu/odata/sap/API_BUSINESS_PARTNER/sap/opu/odata/sap/API_BUSINESS_PARTNER/**A_BusinessPartner('1')
If you see above the resource path /sap/opu/odata/sap/API_BUSINESS_PARTNER is repeated twice. 
The above call passes in java SDK but fails on node.

**Comment by marikaner** [comment] 2023-02-21 09:05
Hey @nipun0212, can you share the code that produced this result? Are you passing the resource path twice?
Please note, that while SAP Cloud SDK for Java and JavaScript fulfil the same tasks, implementation details can differ.

**Comment by nipun0212** [comment] 2023-02-21 09:41
<img width="1724" alt="Screenshot 2023-02-21 at 3 08 13 PM" src="https://user-images.githubusercontent.com/6157690/220307192-d3f2e3d0-c5fb-4350-bf97-125502c04cf0.png">
<img width="1664" alt="Screenshot 2023-02-21 at 3 08 43 PM" src="https://user-images.githubusercontent.com/6157690/220307248-01db0ebe-d4f5-4235-837f-6f16d1d5717e.png">

Hi @marikaner ,
Please check the above snapshot. In both scenarios, the destination URL contains the resource path which URI also contains. In the first snapshot(java one) the request returns the correct output but in the node(javascript) one it says 404 resources not found. Let me know if you need further details.

**Comment by fwilhe** [comment] 2023-02-21 13:34
Hi @nipun0212 

your answer did not really explain how this happens. To me it sounds more like the java sdk is very forgiving here, not sure why that is. I don't think that it is a common feature of http clients to accept repeated path components in an url.

Is there a reason why you can't fix the destination? I think the destination should not have the '/sap/opu/odata/sap/API_BUSINESS_PARTNER' part in its url field and then your code should work just fine in both variants of the SDK.

**Comment by fwilhe** [comment] 2023-02-21 13:38
Also please note that your screenshot contains a password in clear text. I'd always recommend making secrets unreadable when sharing screenshots, even if (I hope) that password is not used for anything serious.

**Comment by jjtang1985** [comment] 2023-02-21 14:44
Hi @nipun0212 ,

I guess the screenshot is deleted now.
Could you please proved a screenshot without confidential information?

Thanks!

**Comment by nipun0212** [comment] 2023-02-21 14:49
Hi @jjtang1985 ,
Updated the screenshot on the same comment without the password.

**Comment by jjtang1985** [comment] 2023-02-21 15:15
Hi @nipun0212 ,

I got some additional information from my colleague @fwilhe.

As @fwilhe mentioned, the root cause of the error from the js side is the url part below, that should not be set in the destination.
In case you have some good reasons (as workaround of other things), it should not be passed in the `requestParams`, making such duplicated URL.

```
/sap/opu/odata/sap/API_BUSINESS_PARTNER
```

I do understand why you felt confusing like "why it worked with java but not for js".
Please note, there is never a contract, that the SAP Cloud SDK Java features (OData, OpenAPI, http client, destination service) will be covered by the SAP Cloud SDK JavaScript or vice versa.
Similarly, please do not assume a function in the Java SDK (`httpClient.execute`) has an equivalent function working in the same way in the JS SDK (`executeHttpRequest`).
In this specific case, I guess java provides additional tolerance, which should be treated as exceptional work around and the JS SDK will not work in the same way.

On the other hand, I see you are consuming BusinessPartner service, where you might be interested in the type safe features of the SDK. See java [doc](https://sap.github.io/cloud-sdk/docs/java/features/odata/v4-vdm-client#basic-crud-operations) and js [doc](https://sap.github.io/cloud-sdk/docs/js/features/odata/v4-client#getall-request-builder).
In addition to the destination service, the type safe features also help build OData entities and requests.
Please reach out, if you are interested so we can share more details.

Thank you very much.

Best regards,
Junjie

**Comment by jjtang1985** [comment] 2023-02-22 08:18
I'll close this issue, as the question is answered.
Please feel free to reopen, if needed.

**Closed by jjtang1985** 2023-02-22 08:18 UTC
Labels: question
