### ISSUE TITLE
Error while generating the odata client

### ISSUE THREAD

**Issue by mahesh0431** [SAP/cloud-sdk-js#3506] opened 2023-02-07 08:21 UTC
**Describe the bug**
While following this documentation: https://api.sap.com/api/SPA_Workflow_Inbox/cloud-sdk/JavaScript
Getting the below error, service-mapping.json error is fine, I can pass the path while calling the execute method, but I am note sure about the other error, related to typings. But note, it is working for me despite the errors. Just wanted to report and see if this will cause any issue.

![image](https://user-images.githubusercontent.com/6804552/217189826-733197e2-7a32-48c0-8644-a19cada9015e.png)

**To Reproduce**
Following these steps:
same as in this documentation: 

**Used Versions:**

- node version via `node -v` v16.18.0
- npm version via `npm -v` 9.1.2
- SAP Cloud SDK version you used as dependency   "@sap-cloud-sdk/generator": "^2.14.0"

**Comment by mahesh0431** [comment] 2023-02-07 09:05
I solved using: npm install --save @types/triple-beam, I guess somewhere dependencies issue? Or am I doing something wrong?

**Comment by fwilhe** [comment] 2023-02-07 09:18
Hi @mahesh0431 

thanks for reporting. I see two issues here.

#### `VALUE_IS_UNDEFINED`

We know that our use of that constant is confusing and we will change this in version 3. [Here](https://github.com/SAP/cloud-sdk-js/pull/3483) is the PR that was already merged on the main branch and will be part of the version 3 release.

For the time being (until v3 is out), have you checked [our documentation](https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-client#generate-a-client-using-the-command-line-interface) for how to deal with `VALUE_IS_UNDEFINED`?

#### Typescript compile errors

This seems to be a transitive dependency of the `winston` logger library we're using. You discovered an issue here, we have not been aware of this. Thanks for reporting.

Manually installing the types as you suggested is a good workaround for the time being, but we'll look into how to fix this properly.

Kind regards

**Comment by mahesh0431** [comment] 2023-02-07 10:32
Awesome!! It looks like the error is coming from today only, yesterday it was fine. About the "VALUE_IS_UNDEFINED
", yes I fixed using service mapping config. But the documentation is not so great I would say, as I spent some time to figure out what I need to pass. 
One more thing, the error related to VALUE_IS_UNDEFINED is not giving any issues when I used the generated client as I can still pass the path in the code manually ("setCustomServicePath") and it works, I hope this is expected.

**Comment by fwilhe** [comment] 2023-02-09 15:48
Hi @mahesh0431 

I just tried to reproduce the typescript compiler issue again but now it seems to be working for me. I could reproduce it before.

Note:

- I removed the package lock json to force npm to get the latest allowed dependency versions as of now
- I did not apply the workaround to manually add `@types/triple-beam` to my dependencies

Can you test if it works for you again given above constraints?

Thanks,
Florian

**Comment by jjtang1985** [comment] 2023-10-04 06:28
I'll close this issue, as it worked.

**Closed by jjtang1985** 2023-10-04 06:28 UTC
Labels: bug
