### ISSUE TITLE
How to filter collection?

### ISSUE THREAD

**Issue by mrnickel** [SAP/cloud-sdk-js#1752] opened 2021-11-02 00:55 UTC
I'm using the generator to generate all my types.

One of the properties of my types is an array of enum values.

interface:
```
selectablePartStatuses: SelectablePartStatuses[];
```

namespace:
```
export const SELECTABLE_PART_STATUSES = _fieldBuilder.buildCollectionField('selectablePartStatuses', SelectablePartStatuses, false);
```

Everything is properly generated.

I'm trying to use the `requestBuilder` to create any ANY query for that property but I cannot for the life of me figure out how to do it.

Thanks so much for your help, and for the creation of this library. It's fantastic!

**Comment by marikaner** [comment] 2021-11-03 09:16
@mrnickel Thank you for your appreciation.

Can you express what you are trying to do as an OData filter string?
I am aware of these filter functions by OData for collections: [here](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc31360980) and [here](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc31360988).
Here is a [list](https://sap.github.io/cloud-sdk/api/1.51.0/modules/sap_cloud_sdk_core#filterFunctionsV4) of functions the SDK supports and [here](https://sap.github.io/cloud-sdk/docs/js/features/odata/use-odata-v4-type-safe-client-for-javascript-typescript#filter-functions) you can find a few examples on how to use them.

Examples:

```ts
import { filterFunctionsV4 } from '@sap-cloud-sdk/core';

// hasSubset
MyEntity.requestBuilder()
  .getAll()
  .filter(filterFunctionsV4.hasSubset(MyEntity.COLLECTION_PROPERTY, [1]));

// length
MyEntity.requestBuilder()
  .getAll()
  .filter(filterFunctionsV4.length(MyEntity.COLLECTION_PROPERTY).equals(3));
```

Hope that helps?

**Comment by mrnickel** [comment] 2021-11-03 15:00
My odata server doesn't support hasSubset.

What I'm trying to do is compose a query that looks like:

```
(selectablePartStatuses/any(s: s eq 'Defective' or s eq 'Good'))
```

**Comment by mrnickel** [comment] 2021-11-03 15:17
For example, looking at the [labmda](https://sap.github.io/cloud-sdk/docs/js/features/odata/use-odata-v4-type-safe-client-for-javascript-typescript#filter-on-one-to-many-navigation-properties) any example, you can filter by a navigation property with `any`

But what if I wanted to search by the **EmailAddress**

Something like:
```
(Person.Emails/any(s: s eq 'email@address.com' or s eq 'emai2l@domain.com'))
```

**Comment by jjtang1985** [comment] 2021-11-03 17:43
Hi @mrnickel ,

It seems you showed an example about the TripPinService.
I think the lambda expression cannot be used with a collection field.

I built a similar request below:
```
https://services.odata.org/TripPinRESTierService/People('russellwhyte')?$expand=Friends&$filter=Friends/Emails/any(e: e eq 'Russell@example.com')
```
If you try it, you'll see an error:
```
{"error":{"code":"","message":"A node of this kind requires the associated property to be a structural, non-collection type, but property 'Emails' is a collection."}}
```
Here is the link to the original OData V4 [documentation](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_LambdaOperators), where it says:
```
OData defines two operators that evaluate a Boolean expression on a collection. Both must be prepended with a navigation path that identifies a collection.
```

**Comment by mrnickel** [comment] 2021-11-03 18:30
@jjtang1985  thanks for that clarification.

How do you suggest that I filter based on a collection that's not a navigation.

For example, a type that contains an array of strings?

```
type Part {
  id: number,
  code: string,
  partStatuses: string[]
}
```

**Comment by mrnickel** [comment] 2021-11-03 18:46
@jjtang1985 further, the following query does work against their service:

`https://services.odata.org/TripPinRESTierService/(S(ts5bnmayur22pucw5llcpuxm))/People('russellwhyte')?$filter=Emails/any(e:%20e%20eq%20%27Russell@example.com%27)`

**Comment by jjtang1985** [comment] 2021-11-03 22:03
@mrnickel ,

Thanks for your working example.
I guess this is not supported for the time being.
I'll discuss it with the team and get back to you soon.

Could you please share your project status (e.g., PoC or Go Live) and your timeline?

For now, I know your odata system does not support `hasSubset` function.
What about this filter function [contains](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_contains), which should work with both string and collection.
Could you check your odata system?

**Comment by mrnickel** [comment] 2021-11-03 23:40
This is a Live project. We're working on writing some more advanced queries to expose some more complicated UI in the application.

Unfortunately it doesn't look like our server supports contains.

**Comment by jjtang1985** [comment] 2021-11-04 07:39
Hi @mrnickel ,

Could you please share your time line for the queries about filtering collections?
Also, have you tried your odata system, so a filter like below works?
```
$filter=partStatuses/any(e: e eq 'status1' or e eq 'status2')
```

**Comment by mrnickel** [comment] 2021-11-04 13:17
@jjtang1985 

Like every project, everything is urgent. We're knee deep in the development right now so it looks like we're going to have to hand roll our complex queries for the time being.


Yes, I have tried our odata system with the above query, works like a charm :-)

Thanks for your help

**Comment by mrnickel** [comment] 2021-11-05 00:22
Looks like that would work, however we'd want to append to the built up filter we've already created.

i.e.

```
People.requestBuilder()
  .getAll()
  .filter(
    .. various filters here ..
  )
  .addCustomerQueryParameters({'$filter': '... whatever else here...'});
  .url(destination)
```

However that would overwrite the existing filters.

Would be nice to appendCustomQueryParameters

**Comment by jjtang1985** [comment] 2021-11-08 16:48
Hi @mrnickel ,

As a flexible/powerful workaround method, the `addCustomerQueryParameters` will overwrite existing query parameters as intended.
Another workaround is:
```ts
// This is an internal api used by us. You can build your filter the same way like the request builder.
// Switch to oDataUriV4, if your service is an odata version 4 service instead of odata version2
    const filterTyped = oDataUriV2.getFilter(People.FIRST_NAME.equals('abc'), People).filter;
// You can then merge the previous filter and any string like below
    const filter = `${filterTyped}&Emails/any(e:%20e%20eq%20'Russell@example.com'))`;
// Eventually, you can set the merged filter.
    const people = await People.requestBuilder()
      .getAll()
      .addCustomQueryParameters({'$filter': filter})
      .url(destination);
```

Please note:
- This is an undocumented internal API, using it for a productive app might be risky.
- `getFilter` handles encoding automatically.

Please let me know your feedback, if possible.

**Comment by artemkovalyov** [comment] 2021-11-09 12:53
Hey, @mrnickel

I'm a PO of the SAP Cloud SDK for JS. I have a couple of quick questions for you as you seem to be an SDK power user:
1. We are soon to release a new major version of the [SDK](https://sap.github.io/cloud-sdk/docs/js/announcing-version-2). 
  - Would you be interested to join the beta testers squad?
  - The migration should require a minimum time and the team will help beta testers with 1st priority.
2. Would you be interested to join a feedback call with the SDK team? If you have any points to share with us, feel free to approach me in person.

We'd also love to hear if the workaround suggested by @jjtang1985 worked for you!

**Comment by jjtang1985** [comment] 2023-10-18 19:12
I'll close this ticket.
Please consider the workaround mentioned.

**Closed by jjtang1985** 2023-10-18 19:12 UTC
Labels: feature request, prio: low
