### ISSUE TITLE
@sap-cloud-sdk/generator: Cannot find name 'ElectronicDocProtocolCodeStrEnum'.

### ISSUE THREAD

**Issue by gregorwolf** [SAP/cloud-sdk-js#1436] opened 2021-07-13 05:58 UTC
I try to generate a custom SAP Cloud SDK OData based on the Metadata from the SAP Business One Service Layer. My sample project is provided here: [sap-business-one-odata-cap  branch real-b1-metadata](https://github.com/gregorwolf/sap-business-one-odata-cap/tree/real-b1-metadata).

1. Clone the above repository
2. run `npm i`
3. run `npm run generate-odata-client`
4. After about 10 minutes you get this error:

```
[2021-07-13T05:54:10.674Z] ERROR    (generator-cli): ErrorWithCause: Generation of services failed.
    at new ErrorWithCause (/Users/gwolf/Documents/Projects/cap/sap-business-one-odata-cap/node_modules/@sap-cloud-sdk/util/dist/error-with-cause.js:32:16)
    at /Users/gwolf/Documents/Projects/cap/sap-business-one-odata-cap/node_modules/@sap-cloud-sdk/generator/dist/generator-cli.js:33:18
Caused by:
Error: Compilation Errors:
/Users/gwolf/Documents/Projects/cap/sap-business-one-odata-cap/srv/odata-client/sapb-1-service/ElectronicDocumentsRequestBuilder.ts:3:502 - error TS2304: Cannot find name 'ElectronicDocProtocolCodeStrEnum'.
/Users/gwolf/Documents/Projects/cap/sap-business-one-odata-cap/srv/odata-client/sapb-1-service/ElectronicDocumentsRequestBuilder.ts:3:502 - error TS4073: Parameter 'code' of public method from exported class has or is using private name 'ElectronicDocProtocolCodeStrEnum'.
/Users/gwolf/Documents/Projects/cap/sap-business-one-odata-cap/srv/odata-client/sapb-1-service/ElectronicDocumentsRequestBuilder.ts:3:2072 - error TS2304: Cannot find name 'ElectronicDocProtocolCodeStrEnum'.
/Users/gwolf/Documents/Projects/cap/sap-business-one-odata-cap/srv/odata-client/sapb-1-service/ElectronicDocumentsRequestBuilder.ts:3:2072 - error TS4073: Parameter 'code' of public method from exported class has or is using private name 'ElectronicDocProtocolCodeStrEnum'.
/Users/gwolf/Documents/Projects/cap/sap-business-one-odata-cap/srv/odata-client/sapb-1-service/ElectronicDocumentsRequestBuilder.ts:3:502 - error TS4073: Parameter 'code' of public method from exported class has or is using private name 'ElectronicDocProtocolCodeStrEnum'.
/Users/gwolf/Documents/Projects/cap/sap-business-one-odata-cap/srv/odata-client/sapb-1-service/ElectronicDocumentsRequestBuilder.ts:3:2072 - error TS4073: Parameter 'code' of public method from exported class has or is using private name 'ElectronicDocProtocolCodeStrEnum'.
    at Object.<anonymous> (/Users/gwolf/Documents/Projects/cap/sap-business-one-odata-cap/node_modules/@sap-cloud-sdk/generator-common/dist/compiler.js:69:31)
    at step (/Users/gwolf/Documents/Projects/cap/sap-business-one-odata-cap/node_modules/@sap-cloud-sdk/generator-common/dist/compiler.js:33:23)
    at Object.next (/Users/gwolf/Documents/Projects/cap/sap-business-one-odata-cap/node_modules/@sap-cloud-sdk/generator-common/dist/compiler.js:14:53)
    at fulfilled (/Users/gwolf/Documents/Projects/cap/sap-business-one-odata-cap/node_modules/@sap-cloud-sdk/generator-common/dist/compiler.js:5:58)
```

Is this an issue with the @sap-cloud-sdk/generator or should we file an incident via SAP Support for SAP Business One as their Metadata may be incorrect?

Best regards
Gregor

**Comment by artemkovalyov** [comment] 2021-07-13 07:02
Hi @gregorwolf,

Thanks for bringing this to us. The specification looks correct and `enum` seems to be a valid property. @jjtang1985  is now looking into details and as a result, we'll have a backlog item to close this gap.

Please, provide us some information about urgency here. As a functional gap, we should take it rather soon. But it's not clear how complicated it is to support this type of property.

**Comment by jjtang1985** [comment] 2021-07-13 07:02
Hi @gregorwolf ,

thanks for the heads-up.

The root cause is that this metadata file is use `enum` as a key of some entities, which is not supported in the SDK.
I'll create a backlog item for it.

As you mentioned, this is a sample app, I would mark it as medium priority.

Best regards,
Junjie

**Comment by gregorwolf** [comment] 2021-07-13 10:37
The sample app is just to share with you quickly. I'm helping an SAP Business One / SAP BTP Customer in an actual project. So it would be great if we can raise the priority.

**Comment by jjtang1985** [comment] 2021-07-13 10:41
@gregorwolf , sure, this ticket is on the top of the backlog now.

**Comment by jjtang1985** [comment] 2021-08-02 05:38
@gregorwolf ,

the fix has been merged and is available if you try the `canary` version.
We'll release a stable version hopefully in this week.

I'll close this ticket, please reopen if you have questions.

Best regards,
Junjie

**Closed by jjtang1985** 2021-08-02 05:38 UTC
Labels: bug, prio: high
