### ISSUE TITLE
Cannot generate SAP Business One OData Client Library with SAP Cloud SDK

### ISSUE THREAD

**Issue by TrinidadMG** [SAP/cloud-sdk-js#696] opened 2020-11-10 13:43 UTC
**Describe the bug**
I have an error when trying to generate SAP Business One OData Client Library with SAP Cloud SDK

**To Reproduce**
I’m following the tutorial Generate Custom OData Client Library with SAP Cloud SDK's Generator for JavaScript: https://developers.sap.com/tutorials/cloudsdk-js-generator.html

1. Take the EDMX file attached here (changed extension to txt to be able to attach it here)
[B1API.edmx.txt](https://github.com/SAP/cloud-sdk-js/files/5517635/B1API.edmx.txt)
2. Create a folder called service-spefication
3. Copy the attached EDMX file into that folder
4. Execute generate-odata-client -i service-specification/ -o odata-client/
5. Error shown in the screen capture
<img width="918" alt="B1CloudSDKError" src="https://user-images.githubusercontent.com/18447094/98680965-6ac51480-2362-11eb-854d-83f1e5f021d6.png">

- The SAP Business One Odata APIs are Odata v4 APIs.
A single EDMX file contains all the entities of the APIs, all in one.

**Used Versions:**
 - SAP Cloud SDK version you used as dependency
@sap-cloud-sdk/cli/0.1.12 win32-x64 node-v12.19.0

**Comment by jjtang1985** [comment] 2020-11-10 13:55
Hi @TrinidadMG , thank you for creating an issue here.
as mentioned in the previous email, I can reproduce the same error with the latest version of the generator and the edmx file provided. Therefore, from the initial investigation I guess it's a bug from our side.
Please wait for the update.

One question from my side, is this a blocker that affects your live system or maybe you are working on some PoC project?

**Comment by gregorwolf** [comment] 2020-11-12 16:31
Hi @jjtang1985,

I've contacted @TrinidadMG because of a SAP B1 customer that wants to create a Customper Portal. He contacted me and as I'm quite deep into the SAP Cloud Application Programming Model I suggested to use CAP. I've started in Spring 2020 and already filed some issues in CAP and the SAP Cloud SDK which where solved. The current state regarding also this issue is reflected in my project [sap-business-one-odata-cap](https://github.com/gregorwolf/sap-business-one-odata-cap). By manually reducing the B1 Service Layer EDMX file we where able to create a version that allows us to consume the B1 Service Layer already in a CAP app. Right now we're consuming the Entity Orders and Businesspartners. So there is no immediate preassuere. But in the long term we want to get rid from our custom EDMX file. And I can forsee also some usecases where we need the Cloud SDK generated access and not only the generic access from CAP.

Best regards
Gregor

**Comment by jjtang1985** [comment] 2020-11-12 17:16
Hi @gregorwolf @TrinidadMG ,

thank you for your updates.

The initial issue shown below was fixed via this [PR](https://github.com/SAP/cloud-sdk-js/pull/699) and released as `canary` version.
```
e.Member.map is not a function
```
However, since our generator does not support entity type as parameter of function/action import, the generator will still fail if you try the `canary` version of our generator.
I created a [ticket](https://github.com/SAP/cloud-sdk-js/issues/707), so that we can work on it.

This issue is on our radar and we will let you know once there are updates.

I'll leave this ticket open now, since the OData client cannot be generated.

**Comment by jjtang1985** [comment] 2020-12-10 14:15
Hi @gregorwolf @TrinidadMG , the [version `1.33.0`](https://github.com/SAP/cloud-sdk-js/releases) has been released. 

In addition to fixing the known enum issue, the unsupported case (using entity type as parameter of function/action imports) is ignored in the generator instead of throwing errors. Therefore, you can try to generate your OData client now.

Please let know, whether the generator works.

For the unsupported entity type, it's still in the backlog and will be handled later.

**Comment by gregorwolf** [comment] 2020-12-11 06:59
Hi @jjtang1985,
thank you for your response. I've directly tested and yes, the generator works now. Takes quite a while due to the huge API of the B1 Service Layer. Check the result at https://github.com/gregorwolf/sap-business-one-odata-cap/tree/master/srv/odata-client/sapb-1-service.

Thanks and best regards
Gregor

**Comment by jjtang1985** [comment] 2020-12-11 07:38
Hi @gregorwolf ,
thank you for your feedback.

I'll close the ticket then.

I'll let you know once there are some updates about the follow up tickets.

Best regards,
Junjie

**Closed by jjtang1985** 2020-12-11 07:38 UTC
Labels: bug, in backlog, needs documentation

**Comment by artemkovalyov** [comment] 2021-02-19 12:32
@TrinidadMG, @gregorwolf, do you guys have a contact point on the Business One side to discuss the sandbox system for us to test some specification details? Or do you just get everything from the API hub?

**Comment by gregorwolf** [comment] 2021-02-19 13:25
Hi @artemkovalyov ,

in the meantime I've created the project [SAP Business One Service Layer Reverse Proxy](https://github.com/gregorwolf/sap-business-one-service-layer-proxy). Just today I've sucessfully tested against the real B1 System. The most important learning was that the SAP Business One Service Layer sends back this two cookies:

```
  "set-cookie": [
    "B1SESSION=5f8cbf40-72b5-11eb-8000-005056ad3b42;HttpOnly;",
    "ROUTEID=.node3; path=/"
  ],
```

So it's not only the session but also the routeid that must be passed back due to the load balancing of the service layer.

I hope that @TrinidadMG can provide you access to a B1 sandbox.

Best regards
Gregor

**Comment by jjtang1985** [comment] 2022-12-01 10:16
Hi @gregorwolf , @TrinidadMG ,

We are happy to share some updates.
The bound functions/actions have been supported from the version 2.11.0 and here is the [link](https://sap.github.io/cloud-sdk/docs/js/release-notes#2110-core-modules---november-16-2022) to the release notes.

With that, the skipped functions/actions can be found in the "action-imports.ts"/"function-imports.ts".
Please check our documentation [here](https://sap.github.io/cloud-sdk/docs/js/features/odata/v4-client#operations-functions-and-actions).
