### ISSUE TITLE
odata-v2: entityBuilder().fromJson() does not recognize sub-sub entities

### ISSUE THREAD

**Issue by drvup** [SAP/cloud-sdk-js#2981] opened 2022-10-20 13:46 UTC
**Describe the bug**
I am on my way to create PurchaseOrders using SAP Cloud SDK and available oData EDMX file. This EDMX is coming from a custom made oData API of an R/3 ERP.

I used `@sap-cloud-sdk/generator` in version 2.5.0 to generate a Virtual-Data-Model first. 

Within I am trying to create a PO by using the ability to create the entity by using the purchaseOrderSetApi.entityBuilder().fromJson() functionality. 

Unfortunately, this is only working for direct navigation properties of the entity
`purchaseOrderHeaderSet`, so it's available for `toPurchaseOrderItem` of the PO, but not for sub-sub entities like `toPurchaseOrderItmAccountAssignment` of `toPurchaseOrderItem`. 

**To Reproduce**
`myVdm.service()purchaseOrderHeaderSetApi.requestBuilder().create(
       myVdm.service().purchaseOrderHeaderSetApi.entityBuilder().fromJson(
               (entityToSendToErp as myVdm.PurchaseOrderHeaderSet)
       )
)`

entityToSendToErp looks like something like that:
{"documentNumber":"4100000333", 
     "toPurchaseOrderItem":
        [
          {"itemNumber":"1","quantity":"90","toPurchaseOrderItmAccountAssignment": 
               [
                     {"glAccountNumber":"80000000","costCenter":"321110"}
               ]
         }
       ],
"isCreate":true}

**Expected behavior**
I did guess, the complete json is getting used and recognized, not only properties and navigations related to the main-entity (available as SCHEMA of the entity). As "toPurchaseOrderItmAccountAssignment" is not identified as part of the SCHEMA of "purchaseOrderHeaderSet" (what's true indeed, because it's part of the item), it get's added as "customField" instead.

Maybe there is another approach to deal with deep-structured json object and getting an entity created from it and I just do not know it ;-)? [Hint](https://github.com/SAP/cloud-sdk/issues/1083).

**Analysis**
I debugged the scenario and discovered file "@sap-cloud-sdk/odata-common/entity-builder", containing method "fromJson()". Here it does check only against the schema of the main-entity, but not of related sub-entities.

**Impact / Priority**
This is blocking our architecture, where we're using json objects to send to the ERP within the SDK.
Affected development phase: 2 weeks before SIT
Impact:  Blocked
Timeline: e.g. Go-Live is in 7 weeks.

**Comment by FrankEssenberger** [comment] 2022-10-20 14:24
Hi @drvup,

regarding deep creates we also found some limitations in the backend systems in the past. If you send a JSON containing Root->lvl1->lv2 is the service creating these entities? Or do you see already that the part is missing in the request being sent to the backend?

As a temporary work around you can use two request and perhaps use the [create as child of](https://sap.github.io/cloud-sdk/docs/js/v1/features/odata/use-odata-v2-type-safe-client-for-javascript-typescript#create-as-child-of). Assuming this is a limitation in the service (to deep created over multiple layers - we are also currently working on batch including referencing requests which should make a efficient solution possible as well).

Best
Frank

**Comment by drvup** [comment] 2022-10-20 14:47
Hi @FrankEssenberger ,

thx for your fast reply. 
I can see `fromJson` is adding lvl2 to lvl1 within the request as `customAttribute`. In my case, unfortunately, this is not working because the ERP expects "ToPurchaseOrderItmAccountAssignment" instead of "toPurchaseOrderItmAccountAssignment" (the first char is in capital). So it's telling me this is not existing. 
This does make sense, as on the SCHEMA of Root, this lvl2 is indeed not existing, as it's part of lvl1 :( 

I tried to get rid of it within [your](https://github.com/SAP/cloud-sdk/issues/1083) approach, but this is not working either.

**Comment by FrankEssenberger** [comment] 2022-10-20 16:30
Ok, I think I got the bug - it should not go to customAttribute and then also the casing should be correct as for proper entities. I guess we do not recursively go over the properties in the `fromJson` method. 

I quickly played around with the BP api which has businessPartner->bpAddress->FaxNumber. If you take the JSON in parts on each API it seems to works:

```ts
const { businessPartnerApi, businessPartnerAddressApi, addressFaxNumberApi } =
  businessPartnerService();

const faxNumber = addressFaxNumberApi
  .entityBuilder()
  .fromJson({ faxNumber: "123" });
const bpAddress = businessPartnerAddressApi
  .entityBuilder()
  .toFaxNumber([faxNumber])
  .fromJson({ streetName: "myStreet" });
const bp = businessPartnerApi
  .entityBuilder()
  .toBusinessPartnerAddress([bpAddress])
  .fromJson({ firstName: "John" });

const deserialized = entityDeserializer(defaultDeSerializers).deserializeEntity(
  bp,
  businessPartnerApi as any
);
console.log(JSON.stringify(deserialized, null, 2));
```

creates teh output:
```json
{
  "toBusinessPartnerAddress": [
    {
      "toFaxNumber": [
        {
          "faxNumber": "123"
        }
      ],
      "streetName": "myStreet"
    }
  ],
  "firstName": "John"
}
```

In which the navigation seem to be correctly desirialized and should be accepted by the backend. This would be a work around until we fixed the issue.

**Comment by FrankEssenberger** [comment] 2022-10-20 16:46
Ok, I think I got the bug - it should not go to customAttribute and then also the casing should be correct as for proper entities. I guess we do not recursively go over the properties in the `fromJson` method.

I quickly played around with the BP api which has businessPartner->bpAddress->FaxNumber. If you take the JSON in parts on each API it seems to works:

```ts
import { businessPartnerService } from "./generated/business-partner-service";
import {
  defaultDeSerializers,
  entityDeserializer
} from "@sap-cloud-sdk/odata-v2/internal";
import {entitySerializer} from "@sap-cloud-sdk/odata-common/"

const { businessPartnerApi, businessPartnerAddressApi, addressFaxNumberApi } =
  businessPartnerService();

const faxNumber = addressFaxNumberApi
  .entityBuilder()
  .fromJson({ faxNumber: "123" });
const bpAddress = businessPartnerAddressApi
  .entityBuilder()
  .toFaxNumber([faxNumber])
  .fromJson({ streetName: "myStreet" });
const bp = businessPartnerApi
  .entityBuilder()
  .toBusinessPartnerAddress([bpAddress])
  .fromJson({ firstName: "John" });

const deserialized = entitySerializer(defaultDeSerializers).serializeEntity(
  bp,
  businessPartnerApi
);
console.log(JSON.stringify(deserialized, null, 2));
```

creates teh output:
```json
{
  "to_BusinessPartnerAddress": [
    {
      "to_FaxNumber": [
        {
          "FaxNumber": "123"
        }
      ],
      "StreetName": "myStreet"
    }
  ],
  "FirstName": "John"
}

```

In which the navigation seem to be correctly serialized and should be accepted by the backend. I only compared to the [spec](https://api.sap.com/api/API_BUSINESS_PARTNER/resource) and the`to_BusinessPartnerAddress` seems to be ok.
This would be a work around until we fixed the issue. 

Best
Frank

**Comment by FrankEssenberger** [comment] 2022-10-21 07:47
GM @drvup,

I just wanted to reproduce the issue so that I can attach some small sample to the issue for the colleague working on it. I tried it with the BP api and have a hard time doing it:

```tsconst bpFromJson = businessPartnerApi
  .entityBuilder()
  .fromJson({
    name: "John",
    toBusinessPartnerAddress: [
      { streetName: "myStreet", toFaxNumber: [{ faxNumber: "123" }] },
    ],
  });
deserialized = entitySerializer(defaultDeSerializers).serializeEntity(
  bpFromJson,
  businessPartnerApi
);
console.log(JSON.stringify(deserialized, null, 2));
```

Leads a correct serialized object without a `customAttribute` (same output as above). Could you perhaps provide the service spec (you mentioned it is custom) to us so that we can reproduce the issue? In case it is sensitive you can send it via Email -> fristName.lastName@sap.com is the pattern :-). Best also with a minimal JSON used as `entityToSendToErp` in your example from the beginning.

Best
Frank

**Comment by drvup** [comment] 2022-10-21 07:50
Will do so and send it to you today :)

**Comment by FrankEssenberger** [comment] 2022-10-21 13:09
I had a quick look and I think, I found the reason for the problem. We do some [lazy init](https://github.com/SAP/cloud-sdk-js/blob/f76da306088050ab10a90622b45fe46cc3d04d6e/test-packages/test-services-odata-v2/test-service/service.ts#L176) of navigation properties. This means the second layer is not initialized. If I added a 

```ts
const {purchaseOrderHeaderSetApi,purchaseOrderItemSetApi} = bragZciContentService();

const order = purchaseOrderHeaderSetApi.entityBuilder().fromJson({documentNumber:"1234",toPurchaseOrderItem:[{itemNumber:"1",toPurchaseOrderItmAccountAssignment:[{glAccountNumber:"5678"}]}]})

const deserialized = entitySerializer(defaultDeSerializers).serializeEntity(
    order,
    purchaseOrderHeaderSetApi
);
console.log(JSON.stringify(deserialized, null, 2));

```

it worked even if the `purchaseOrderItemSetApi` is not used. If I remember correctly we had some issue by you reported in the past already which lead to [this docu entry](https://sap.github.io/cloud-sdk/docs/js/features/odata/execute-odata-request#deserialize-nested-navigation-properties). 

I hope this works as a quick work around and we will see if this is fixable with not to much effort. The `fromJson()` method is a bit try since it breaks the typed approach a bit.

Best
Frank

**Comment by drvup** [comment] 2022-10-21 13:54
Hi @FrankEssenberger ,
thanks for coming back to me about this issue. 
Yes, you're right. I identified the lazy init stuff and I made the same mistake here again ;-) 

Anyhow, of course with this approach the all-time generic approach is lost. But that's a perfect way to mitigate the issue while you and the team is checking abilities to solve the `fromJson()` part. Maybe it's worth to highlight that at the documentation on the related part ;-) 
Lazy developers like me can identify this issue easier and maybe check out available approaches like we did discuss now :D 

However, thanks for pointing this out and thanks for the great support. This is really appreciated :) 

Best,
Cedric

**Comment by FrankEssenberger** [comment] 2022-10-21 14:23
I would not call this a mistake because it is not clear from the `fromJson()` that you have to initialize something. If we keep this method in newer higher versions we either need to make this clear from the API or make it capable of initializing the object. However, we had issues with cycle references along the way.

**Comment by jjtang1985** [comment] 2024-02-15 10:04
I'll close the issue, as it was solved.

**Closed by jjtang1985** 2024-02-15 10:04 UTC
Labels: bug
