### ISSUE TITLE
getAxiosConfigWithDefaultsWithoutMethod sets paramsSerializer without proper encoding

### ISSUE THREAD

**Issue by richardscholten** [SAP/cloud-sdk-js#1737] opened 2021-10-26 13:16 UTC
In our code we use the `buildAxiosRequestConfig` to get a preconfigured `AxiosRequestConfig`. It calls this method that does not encode the query parameters keys or values:

https://github.com/SAP/cloud-sdk-js/blob/962e0437bd63a0551dc6ff8255313d94c126b8f3/packages/http-client/src/http-client.ts#L231-L244

This results in this error when a query parameter for example contains spaces:

```
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:147:13)
    at Object.request (https.js:316:10)
```

It is not clear to me why this `paramsSerializer` is set while Axios itself already encodes parameters by default:

https://github.com/axios/axios/blob/master/lib/helpers/buildURL.js

**To Reproduce**

1. Call `buildAxiosRequestConfig` to get a AxiosRequestConfig.
2. Execute a GET request with Axios using a parameter containing disallowed characters (spaces for example) and the config from step 1.
3. Confirm that the query parameters are indeed not encoded.
4. See that ERR_UNESCAPED_CHARACTERS is thrown.

**Expected behavior**

Query parameters are encoded and request succeeds.

**Used Versions:**

- node version via `node -v`: v12.21.0
- npm version via `npm -v`: 6.14.11
- SAP Cloud SDK version you used as dependency: 1.51.0

**Code Examples**

```
const requestConfig = await buildAxiosRequestConfig(destination);
requestConfig.params = {
  test: 'param with spaces' 
}
const response = await axios.get('...some url...', requestConfig);
```

**Log file**

```
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:147:13)
    at Object.request (https.js:316:10)
    at RedirectableRequest._performRequest (...\node_modules\follow-redirects\index.js:272:24)
    at new RedirectableRequest (...\node_modules\follow-redirects\index.js:61:8)
    at Object.request (...\node_modules\follow-redirects\index.js:463:14)
    at dispatchHttpRequest (...\node_modules\axios\lib\adapters\http.js:202:25)
    at new Promise (<anonymous>)
    at httpAdapter (...\node_modules\axios\lib\adapters\http.js:46:10)
    at dispatchRequest (...\node_modules\axios\lib\core\dispatchRequest.js:53:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Impact / Priority**

Impact for us is low, because we already added this workaround:

```
const config = await buildAxiosRequestConfig(destination);
config.paramsSerializer = undefined;
return config;
```

General impact is probably high, because a test does not catch this error when you use values that do not need encoding.

**Comment by FrankEssenberger** [comment] 2022-03-11 10:44
Hi @richardscholten we included encoding on the query parameters in this PR https://github.com/SAP/cloud-sdk-js/pull/2183
The custom query parameters are not encoded on purpose in case you want to enforce something on a strangly behaving backend. 

If you want to encode everything you can pass the `encodeAllParameters` as described [here](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/query-parameters#encoding)

I hope this fixes your needs. The change is already availible as `canary` version on npm or in a few days when we make a new minor version release of version 2.X.Y of the SDK.

Best
Frank

**Comment by FrankEssenberger** [comment] 2022-03-11 10:45
I close the issue for the moment. In case the problem is not solved please reopen it.

**Closed by FrankEssenberger** 2022-03-11 10:45 UTC
Labels: bug, prio: medium
