### ISSUE TITLE
Tutorial: Accessing API Hub S/4HANA Sandbox system 

### ISSUE THREAD

**Issue by karstenschneider01** [SAP/cloud-sdk-js#2896] opened 2022-09-22 08:44 UTC
Hello Team,
I’m trying to follow the [Getting Started Tutorial for SAP Cloud SDK for JS](https://sap.github.io/cloud-sdk/docs/js/tutorials/getting-started/execute-an-odata-request) (using VS Code) but I’m not able to get it working. In the tutorial we implement the BusinessPartnerController to access the S/4HANA Cloud on API Business Hub. This is not working; I get the error message:
{
  "statusCode": 500,
  "message": "Failed to get business partners - get request to https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER failed! "
}
(as defined in the catch-block of the bp controller).
I tried also accessing the above URL with the APIKey in the header in Postman which works fine.

**Used Versions:**

- node version via `node -v` -> v16.17.0
- npm version via `npm -v` -> 8.19.2
- SAP Cloud SDK version -> newset, installed via npm

You can find the code here:
https://github.tools.sap/D057772/sap-cloud-sdk-0921

Best regards
Karsten

**Comment by jjtang1985** [comment] 2022-09-23 15:30
Hi @karstenschneider01 ,

Thanks for raising up.
I can reproduce the issue with the root cause:
```
Request failed with status code 502
```
@marikaner , FYI.

**Comment by jjtang1985** [comment] 2022-09-23 16:03
Hi @karstenschneider01 ,

I can fix it by adding a line in the `business-partners.service.ts`, so we pick the top one entity.

```ts
    .getAll()
// add this
    .top(1)
    .addCustomHeaders()
```
Could you please try it?

**Comment by karstenschneider01** [comment] 2022-09-27 10:41
Hi Junjie,

yes that works! Thank you so much for the quick response!
Is this how it is supposed to be? Do I always have to supply a number of Objects that I want to use?
I'll play around with that a little and keep you updated.

Many thanks so far and best regards,
Karsten

**Comment by jjtang1985** [comment] 2022-09-27 17:07
Hi @karstenschneider01 ,

It's great to see your test is working now.

> Do I always have to supply a number of Objects that I want to use?

This is a specific case for the sandbox system.
I made an HTTP request and see the error message.

I'll close this ticket now.

BR,
Junjie

**Closed by jjtang1985** 2022-09-27 17:07 UTC
Labels: bug
